### ISSUE TITLE
Form not posting (contacts)

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued-skeleton#111]
How to reproduce:

- go to `/contacts/list`
- click `add company`
- search for vaizard & click on it
- see vaizard getting prefilled
- save it
- instead of seeing the posted data, the request body is empty (same also when lookin at the request with developer console).

My guess is, that the typeahead javascript and the form posting javascript interfere (if I move the <form> on https://github.com/vaizard/glued-skeleton/blob/master/glued/Contacts/Views/Partials/contacts_items_modal.twig#L25 above the div with the typeahead input, just after https://github.com/vaizard/glued-skeleton/blob/master/glued/Contacts/Views/Partials/contacts_items_modal.twig#L3) i see the search string in the typeahead posted. but never the data from the form below.

**Comment by pohadkar** [comment]
ta stranka je cela nejaka pochybna. uz pri zobrazeni tam hazi react nejakou chybu. dival jsem se co to je za chybu
https://reactjs.org/docs/error-decoder.html/?invariant=200
a vypada to, ze se cili nejaky neexistujici dom element.
takze se podivam na html sablony. mozna nemas nekde neco uzavrene.

**Comment by pohadkar** [comment]
chyba byla ve spatnem html modalu
pak v nazvu promenne, ktera se dosazovala do id formu
a prvkum ve formu dale chybelo name, takze serialize nemela z ceho vytvorit asociativni pole

**Comment by killua-eu** [comment]
fixed
