### ISSUE TITLE
Silent upload failure in stor

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued-skeleton#186]
Upload file size exceeding php ini config results in

```
[Mon Feb 01 22:44:47.500253 2021] [php7:warn] [pid 367] [client 10.146.149.1:57346] PHP Warning:  POST Content-Length of 11218658 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer: https://10.146.149.150/stor/browser?filter=/fin_trx/185634
```

upload needs a try/catch wrapper and return a json with a propper error message

**Comment by pohadkar** [comment]
osetreno rozsirenim ajax volani o error handling
message tisknu do toastu
mozne rozsireni v budoucnu, umoznit v toastu menit barvy nastavenim nejake class

**Comment by killua-eu** [comment]
seriously needs better coding standards

**Comment by killua-eu** [comment]
Improved a bit with 116340c
