### ISSUE TITLE
Post upload is not working

### ISSUE THREAD

**Issue by zelitomas** [vaizard/glued-skeleton#40]
Ideal solution: remove feature entirely. Difference between AJAX and POST is confusing for user anyway.

**Comment by killua-eu** [comment]
yep, kill it with fire please, @pohadkar.

**Comment by zelitomas** [comment]
Just a friendly reminder - the issue is still there.

**Comment by killua-eu** [comment]
all leftovers of the post upload should be removed by now. should you encounter some more, feel free to open a new issue.
