### ISSUE TITLE
Dockerize glued

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued-skeleton#44]
Yes I hate docker, but setting things up on an unfamiliar distro without ansible is such a pain.. @zelitomas , feel like helping out?

**Comment by killua-eu** [comment]
- [x] config moved to a spearate directory for nice voluming
- [] add support for merging dist config and local config
- [] modify composer.json to keep the install streamlined from shell but still allow non-interactive dockerfiling

**Comment by zelitomas** [comment]
Please check [zelitomas/glued-skeleton/dockerize](/zelitomas/glued-skeleton/tree/dockerize) - it is starting now, but there is some bug in your app that is way beyond my PHP knowledge and way way way beyond my willingness to fix.

(to start dockerized version, use `docker-compose up --build`)
