### ISSUE TITLE
Glued doesn't run on a port different than 80

### ISSUE THREAD

**Issue by zelitomas** [vaizard/glued-skeleton#66]
# Steps to reproduce

* Run Glued using default docker compose configuration (`docker-compose up --build`)
* Open http://localhost:8080/core/signup
* Submit registration form

# Expected behaviour

* User is registered and redirected to http://localhost:8080

# Actual behaviour

*  User is registered and redirected to http://localhost (default port)

**Comment by killua-eu** [comment]
Well. I've seen it, but I cant reproduce it now. Can you?

**Comment by zelitomas** [comment]
Yes, it happened to me yesterday.

If you are already registered, maybe try deleting MySQL container and start from scratch again...

24. 9. 2020 12:30, 12:30, killua-eu <notifications@github.com> napsal/a:

**Comment by zelitomas** [comment]
I also remember you setting the port to 80 in docker-compose.yml. Maybe you forgot to set it back to 8080??

**Comment by killua-eu** [comment]
Hmm maybe it was on sign up only. Signing in redirects correctly.
