### ISSUE TITLE
Stor / CAS mechanism doesn't work right

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued-skeleton#93]
- upload file.jpg 
- upload file.jpg again into same path.

Expected behaviour:

- [x] a single file in private/stor/ (this works)
- [ ] a single entry in t_stor_objects (this doesnt work, no hash comparison I guess?)
- [ ] t_stor_objects identified by id (no c_uid column exists). Whats the connection between t_stor_objects and t_stor_links?
- [ ] if data (hash) and filename is the same, we should get also only a single entry in t_stor_links (file aready exists, why have it there again?)

CAS concept overview:

- file1/hash1 + file1/hash1 + both in same dir => 1 entry in t_stor_objects, 1 in t_stor_links
- file1/hash1 + file1/hash1 + each in diff dir => 1 entry in t_stor_objects, 2 in t_stor_links
- file1/hash1 + file2/hash1 + both in same dir => 1 entry in t_stor_objects, 2 in t_stor_links
- file1/hash1 + file1/hash2 + both in same dir => 2 entries in t_stor_objects, 2 in t_stor_links (mark as revisions - we don't have sql designed for this yet)

**Comment by pohadkar** [comment]
vyzkouseno a jelo mi to.
je mozne ze se to tykalo POST zpusobu uploadu a nebo neceho co uz je opraveno z minula.
zrusil jsem post upload souboru ve stor browseru.
jeste je pouzity ve worklogu. az budu opravovat worklog, zrusim to uplne.

**Comment by killua-eu** [comment]
reviewed, tested, works. Wft happened doesnt happen any more.
